version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo
    
    php:
      version: 7.4.6

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: brew install phpunit
      - run: phpunit --bootstrap src/Email.php tests
      
              
