version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run:
            command: |
              mkdir -p ~/phpunit
              phpunit --log-junit --bootstrap src/Email.php tests
            when: always
        - store_test_results:
            path: ~/phpunit
        - store_artifacts:
            path: ~/phpunit    
