version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: "Running Jest Tests..."
          command: yarn test

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: 
          name: "Installing PHPUnit"
          command: composer require --dev phpunit/phpunit ^7

      - run: 
          name: "Running PHP Unit tests.."
          command: ./vendor/bin/phpunit --bootstrap src/Email.php tests

      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Running PHPCS
          command: bash ./.circleci/phpcs.sh